### ISSUE TITLE
APT source whitelist request for ppa:spotify-jyrki/dh-virtualenv

### ISSUE THREAD

**Issue by bivald** [travis-ci/apt-source-safelist#281]
deb http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu trusty main 
deb-src http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu trusty main

**Comment by bivald** [comment]
This would allow us to not use sudo mode, i.e we can move into the container infrastructure

**Comment by parasyte** [comment]
@BanzaiMan ping. Is there anything we can do here to help move this forward?

**Comment by bivald** [comment]
Closing, if it's not merged in 5 years it's not going to be :)
