### ISSUE TITLE
ubuntu-toolchain-r-test is not whitelisted in xenial 

### ISSUE THREAD

**Issue by patrickelectric** [travis-ci/apt-source-safelist#383]
https://travis-ci.org/bluerobotics/ping-viewer/jobs/389862004

**Comment by nth10sd** [comment]
I confirm this on Travis images with `dist: xenial`:

```
Adding APT Sources (BETA)
Disallowing sources: ubuntu-toolchain-r-test
To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
```

**Comment by acgetchell** [comment]
Yes, please fix, this makes the xenial image unusable for modern C++ development.

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/412781334#L425

**Comment by Kagami** [comment]
Use `sourceline: "ppa:ubuntu-toolchain-r/test"` instead of `ubuntu-toolchain-r-test` as a quick fix.

**Comment by concatime** [comment]
Can someone confirm if this issue is solved?

**Comment by acgetchell** [comment]
It's solved.

https://github.com/acgetchell/CDT-plusplus/blob/develop/.travis.yml#L9

**Comment by concatime** [comment]
@patrickelectric Please close this issue.

**Comment by patrickelectric** [comment]
:mailbox_closed:

**Comment by Flamefire** [comment]
Happening again

**Comment by mhx** [comment]
Can confirm this is happening again. Turns out Travis is not only hard to set up, it's also surprisingly brittle. :/

**Comment by rafecolton** [comment]
Happening to us as well. https://github.com/travis-ci/apt-source-safelist/issues/383#issuecomment-412699538 seems to be working.

**Comment by thebigG** [comment]
Just happened to me last night as well.

**Comment by patrickelectric** [comment]
📫

**Comment by thebigG** [comment]
UPDATE:It works for me now. Running Ubuntu trusty(14.04).
Here's my config file:https://github.com/thebigG/Tasker/blob/master/.travis.yml

**Comment by rafecolton** [comment]
@thebigG 

> UPDATE:It works for me now.

We were only seeing this on travis-ci.com and that looks like a public repo, so I would expect it to work fine on travis-ci.org. Does this also work for you on private repos?

**Comment by thebigG** [comment]
@rafecolton 
I don't have any private repos that use TravisCI at the moment. Just this public one.

**Comment by patrickelectric** [comment]
Closing :mailbox_closed:

**Comment by rafecolton** [comment]
@patrickelectric why are you closing the issue? Has it been fixed?

**Comment by rafecolton** [comment]
> I would think it would also work on private repos.

It does not, unless it has been fixed. See https://github.com/travis-ci/apt-source-safelist/issues/383#issuecomment-608517861

**Comment by AndreiCherniaev** [comment]
> Use `sourceline: "ppa:ubuntu-toolchain-r/test"` instead of `ubuntu-toolchain-r-test` as a quick fix.
1) sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E9377A2BA9EF27F

2) sudo nano /etc/apt/sources.list
I add last 2 lines:

deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main 
deb-src http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main 

So now [I can](https://habr.com/ru/post/549886/) using gcc-9 and g++-9
