### ISSUE TITLE
Please add llvm-toolchain-trusty-7 to the whitelist.

### ISSUE THREAD

**Issue by Kangz** [travis-ci/apt-source-safelist#386]
LLVM just branched version 7 to a different APT repo. Please add it to the whitelist!

It is defined on [apt.llvm.org](http://apt.llvm.org/).

```json
  {
    "alias": "llvm-toolchain-trusty-7",
    "sourceline": "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main",
    "key_url": "http://apt.llvm.org/llvm-snapshot.gpg.key"
  },
```

**Comment by pavelkryukov** [comment]
> `"sourceline": "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6 main",`

Do you mean `"sourceline": "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main",`?

**Comment by ekrich** [comment]
Is `llvm-toolchain-trusty-6.0` already supported?

**Comment by concatime** [comment]
Up.

**Comment by akimd** [comment]
Wake up.

**Comment by PragmaTwice** [comment]
Up.
I want clang-7.0 in llvm-toolchain-trusty-7.

**Comment by offa** [comment]
There's a pending PR now: #392

**Comment by sylvestre** [comment]
It landed. This bug can be closed.

**Comment by pavelkryukov** [comment]
@psi29a They changed spelling, it is `llvm-toolchain-trusty-7`, without a dot-zero

**Comment by psi29a** [comment]
Cheers! Thanks :)
