### ISSUE TITLE
Please whitelist repository "llvm-toolchain-xenial" for Clang >=9 on Ubuntu xenial

### ISSUE THREAD

**Issue by hartwork** [travis-ci/apt-source-safelist#407]
Hi!

`llvm-toolchain-trusty` (without a number) for Clang 9 on Ubuntu `trusty` [is there](https://github.com/sylvestre/apt-source-whitelist/blob/ad239bcda10380d865e36148a7e8dbf8ea1ea0db/ubuntu.json#L292-L297), but `llvm-toolchain-xenial` (without a number) for Clang 9 on Ubuntu `xenial` — as I read https://apt.llvm.org/ — is still [disallowed](https://travis-ci.org/uriparser/uriparser/builds/555952912#L160).

Any chance it could be added?

Thanks!

Related: #392 #399

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
There's a pull request for review at #408 now. Thank you!

**Comment by saprykin** [comment]
Could you please also whitelist llvm-toolchain-xenial-9 ?

**Comment by mbrucher** [comment]
Almost time to whitelist the version 10! Why is this still pending?

**Comment by hartwork** [comment]
It makes me sad that this trivial-to-fix issue is still open 10 months later. What does it take to get this fixed?

**Comment by hartwork** [comment]
Closing, does not seem relevant any more
